#!/usr/bin/env python3
"""Generate a printable Basketball Dice v0.5 matchup game card as HTML plus CSV tables.
No third-party dependencies.

Example:
  python generate_game_card.py --away Thunder --home Knicks --outdir generated_cards
"""
import argparse, csv, html, math, os
PARAMS = {'global_shot_mod':-1,'global_fd_mod':1,'global_tov_mod':0,'tov_scale':1.0,'fd_scale':1.0,'three_mod':0,'orb_base':27,'ast_mod':0,'block_base':7,'steal_turnover_pct':60,'nonshoot_foul_chance':7,'defense_shot_divisor':2.0,'max_orb_extensions':2}
TEAM_ROWS = [{'3PT Tend': 1,
  'AST': 57,
  'Abbr': 'OKC',
  'DEF': 5,
  'DRB': 2,
  'DRtg': 107.5,
  'Foul Disc': 1,
  'Foul Draw': 1,
  'ORB': 0,
  'ORtg': 120.3,
  'Pace': 100.0,
  'ShotQ': 1,
  'TO Press': 2,
  'TO Protect': 1,
  'Team': 'Thunder'},
 {'3PT Tend': 1,
  'AST': 56,
  'Abbr': 'NYK',
  'DEF': 1,
  'DRB': 0,
  'DRtg': 114.3,
  'Foul Disc': 0,
  'Foul Draw': 1,
  'ORB': 2,
  'ORtg': 118.5,
  'Pace': 96.7,
  'ShotQ': 1,
  'TO Press': 1,
  'TO Protect': 1,
  'Team': 'Knicks'},
 {'3PT Tend': 4,
  'AST': 62,
  'Abbr': 'BOS',
  'DEF': 3,
  'DRB': 1,
  'DRtg': 111.1,
  'Foul Disc': 1,
  'Foul Draw': -1,
  'ORB': -1,
  'ORtg': 120.6,
  'Pace': 95.7,
  'ShotQ': 2,
  'TO Press': 1,
  'TO Protect': 1,
  'Team': 'Celtics'},
 {'3PT Tend': -1,
  'AST': 66,
  'Abbr': 'DEN',
  'DEF': -1,
  'DRB': 0,
  'DRtg': 116.0,
  'Foul Disc': -1,
  'Foul Draw': 1,
  'ORB': 0,
  'ORtg': 119.9,
  'Pace': 99.8,
  'ShotQ': 2,
  'TO Press': 0,
  'TO Protect': 2,
  'Team': 'Nuggets'}]
PLAYER_ROWS = [{'2P': 55,
  '3F': 26,
  '3P': 37,
  'ASTw': 35,
  'BLKw': 6,
  'DREBw': 8,
  'FD': 15,
  'FT': 90,
  'OREBw': 2,
  'PFw': 7,
  'Player': 'Shai Gilgeous-Alexander',
  'STLw': 18,
  'TOV': 8,
  'Team': 'Thunder',
  'Use': 27},
 {'2P': 53,
  '3F': 31,
  '3P': 37,
  'ASTw': 22,
  'BLKw': 5,
  'DREBw': 10,
  'FD': 7,
  'FT': 80,
  'OREBw': 4,
  'PFw': 7,
  'Player': 'Jalen Williams',
  'STLw': 12,
  'TOV': 10,
  'Team': 'Thunder',
  'Use': 18},
 {'2P': 58,
  '3F': 48,
  '3P': 38,
  'ASTw': 8,
  'BLKw': 24,
  'DREBw': 18,
  'FD': 7,
  'FT': 75,
  'OREBw': 13,
  'PFw': 8,
  'Player': 'Chet Holmgren',
  'STLw': 7,
  'TOV': 9,
  'Team': 'Thunder',
  'Use': 12},
 {'2P': 46,
  '3F': 75,
  '3P': 41,
  'ASTw': 6,
  'BLKw': 3,
  'DREBw': 8,
  'FD': 3,
  'FT': 72,
  'OREBw': 5,
  'PFw': 9,
  'Player': 'Luguentz Dort',
  'STLw': 12,
  'TOV': 8,
  'Team': 'Thunder',
  'Use': 8},
 {'2P': 58,
  '3F': 1,
  '3P': 0,
  'ASTw': 12,
  'BLKw': 8,
  'DREBw': 19,
  'FD': 6,
  'FT': 68,
  'OREBw': 18,
  'PFw': 11,
  'Player': 'Isaiah Hartenstein',
  'STLw': 4,
  'TOV': 12,
  'Team': 'Thunder',
  'Use': 7},
 {'2P': 48,
  '3F': 55,
  '3P': 36,
  'ASTw': 8,
  'BLKw': 2,
  'DREBw': 5,
  'FD': 3,
  'FT': 78,
  'OREBw': 3,
  'PFw': 5,
  'Player': 'Cason Wallace',
  'STLw': 12,
  'TOV': 9,
  'Team': 'Thunder',
  'Use': 7},
 {'2P': 50,
  '3F': 60,
  '3P': 35,
  'ASTw': 10,
  'BLKw': 2,
  'DREBw': 6,
  'FD': 3,
  'FT': 82,
  'OREBw': 3,
  'PFw': 6,
  'Player': 'Alex Caruso',
  'STLw': 14,
  'TOV': 11,
  'Team': 'Thunder',
  'Use': 5},
 {'2P': 45,
  '3F': 80,
  '3P': 41,
  'ASTw': 4,
  'BLKw': 1,
  'DREBw': 3,
  'FD': 2,
  'FT': 80,
  'OREBw': 1,
  'PFw': 3,
  'Player': 'Isaiah Joe',
  'STLw': 6,
  'TOV': 6,
  'Team': 'Thunder',
  'Use': 7},
 {'2P': 57,
  '3F': 42,
  '3P': 38,
  'ASTw': 8,
  'BLKw': 3,
  'DREBw': 7,
  'FD': 4,
  'FT': 79,
  'OREBw': 5,
  'PFw': 5,
  'Player': 'Aaron Wiggins',
  'STLw': 7,
  'TOV': 7,
  'Team': 'Thunder',
  'Use': 9},
 {'2P': 51,
  '3F': 32,
  '3P': 38,
  'ASTw': 32,
  'BLKw': 1,
  'DREBw': 5,
  'FD': 12,
  'FT': 82,
  'OREBw': 1,
  'PFw': 6,
  'Player': 'Jalen Brunson',
  'STLw': 8,
  'TOV': 9,
  'Team': 'Knicks',
  'Use': 27},
 {'2P': 58,
  '3F': 38,
  '3P': 42,
  'ASTw': 14,
  'BLKw': 10,
  'DREBw': 24,
  'FD': 10,
  'FT': 83,
  'OREBw': 15,
  'PFw': 9,
  'Player': 'Karl-Anthony Towns',
  'STLw': 5,
  'TOV': 11,
  'Team': 'Knicks',
  'Use': 22},
 {'2P': 52,
  '3F': 45,
  '3P': 36,
  'ASTw': 12,
  'BLKw': 3,
  'DREBw': 8,
  'FD': 5,
  'FT': 82,
  'OREBw': 3,
  'PFw': 6,
  'Player': 'Mikal Bridges',
  'STLw': 12,
  'TOV': 8,
  'Team': 'Knicks',
  'Use': 16},
 {'2P': 54,
  '3F': 48,
  '3P': 37,
  'ASTw': 8,
  'BLKw': 4,
  'DREBw': 9,
  'FD': 5,
  'FT': 78,
  'OREBw': 5,
  'PFw': 8,
  'Player': 'OG Anunoby',
  'STLw': 13,
  'TOV': 9,
  'Team': 'Knicks',
  'Use': 15},
 {'2P': 55,
  '3F': 20,
  '3P': 33,
  'ASTw': 14,
  'BLKw': 2,
  'DREBw': 17,
  'FD': 4,
  'FT': 75,
  'OREBw': 10,
  'PFw': 7,
  'Player': 'Josh Hart',
  'STLw': 9,
  'TOV': 10,
  'Team': 'Knicks',
  'Use': 9},
 {'2P': 47,
  '3F': 60,
  '3P': 39,
  'ASTw': 7,
  'BLKw': 1,
  'DREBw': 4,
  'FD': 2,
  'FT': 83,
  'OREBw': 2,
  'PFw': 3,
  'Player': 'Miles McBride',
  'STLw': 6,
  'TOV': 7,
  'Team': 'Knicks',
  'Use': 5},
 {'2P': 65,
  '3F': 0,
  '3P': 0,
  'ASTw': 2,
  'BLKw': 16,
  'DREBw': 18,
  'FD': 8,
  'FT': 55,
  'OREBw': 20,
  'PFw': 8,
  'Player': 'Mitchell Robinson',
  'STLw': 5,
  'TOV': 13,
  'Team': 'Knicks',
  'Use': 4},
 {'2P': 54,
  '3F': 10,
  '3P': 30,
  'ASTw': 2,
  'BLKw': 7,
  'DREBw': 10,
  'FD': 5,
  'FT': 64,
  'OREBw': 11,
  'PFw': 5,
  'Player': 'Precious Achiuwa',
  'STLw': 4,
  'TOV': 13,
  'Team': 'Knicks',
  'Use': 2},
 {'2P': 53,
  '3F': 48,
  '3P': 37,
  'ASTw': 22,
  'BLKw': 5,
  'DREBw': 16,
  'FD': 8,
  'FT': 83,
  'OREBw': 7,
  'PFw': 6,
  'Player': 'Jayson Tatum',
  'STLw': 9,
  'TOV': 9,
  'Team': 'Celtics',
  'Use': 25},
 {'2P': 54,
  '3F': 35,
  '3P': 35,
  'ASTw': 14,
  'BLKw': 4,
  'DREBw': 11,
  'FD': 8,
  'FT': 76,
  'OREBw': 5,
  'PFw': 7,
  'Player': 'Jaylen Brown',
  'STLw': 10,
  'TOV': 10,
  'Team': 'Celtics',
  'Use': 22},
 {'2P': 52,
  '3F': 58,
  '3P': 38,
  'ASTw': 20,
  'BLKw': 9,
  'DREBw': 7,
  'FD': 5,
  'FT': 84,
  'OREBw': 3,
  'PFw': 6,
  'Player': 'Derrick White',
  'STLw': 10,
  'TOV': 7,
  'Team': 'Celtics',
  'Use': 15},
 {'2P': 59,
  '3F': 44,
  '3P': 40,
  'ASTw': 7,
  'BLKw': 18,
  'DREBw': 15,
  'FD': 9,
  'FT': 82,
  'OREBw': 9,
  'PFw': 8,
  'Player': 'Kristaps Porzingis',
  'STLw': 4,
  'TOV': 9,
  'Team': 'Celtics',
  'Use': 14},
 {'2P': 52,
  '3F': 55,
  '3P': 36,
  'ASTw': 18,
  'BLKw': 3,
  'DREBw': 8,
  'FD': 3,
  'FT': 83,
  'OREBw': 4,
  'PFw': 6,
  'Player': 'Jrue Holiday',
  'STLw': 14,
  'TOV': 8,
  'Team': 'Celtics',
  'Use': 9},
 {'2P': 49,
  '3F': 65,
  '3P': 41,
  'ASTw': 12,
  'BLKw': 1,
  'DREBw': 5,
  'FD': 2,
  'FT': 84,
  'OREBw': 3,
  'PFw': 4,
  'Player': 'Payton Pritchard',
  'STLw': 7,
  'TOV': 6,
  'Team': 'Celtics',
  'Use': 7},
 {'2P': 55,
  '3F': 70,
  '3P': 36,
  'ASTw': 8,
  'BLKw': 8,
  'DREBw': 11,
  'FD': 2,
  'FT': 80,
  'OREBw': 5,
  'PFw': 7,
  'Player': 'Al Horford',
  'STLw': 5,
  'TOV': 7,
  'Team': 'Celtics',
  'Use': 4},
 {'2P': 48,
  '3F': 82,
  '3P': 41,
  'ASTw': 3,
  'BLKw': 1,
  'DREBw': 5,
  'FD': 1,
  'FT': 78,
  'OREBw': 2,
  'PFw': 4,
  'Player': 'Sam Hauser',
  'STLw': 4,
  'TOV': 5,
  'Team': 'Celtics',
  'Use': 3},
 {'2P': 66,
  '3F': 0,
  '3P': 0,
  'ASTw': 3,
  'BLKw': 10,
  'DREBw': 8,
  'FD': 5,
  'FT': 65,
  'OREBw': 9,
  'PFw': 8,
  'Player': 'Luke Kornet',
  'STLw': 2,
  'TOV': 10,
  'Team': 'Celtics',
  'Use': 1},
 {'2P': 62,
  '3F': 25,
  '3P': 42,
  'ASTw': 45,
  'BLKw': 8,
  'DREBw': 27,
  'FD': 10,
  'FT': 80,
  'OREBw': 15,
  'PFw': 7,
  'Player': 'Nikola Jokic',
  'STLw': 8,
  'TOV': 12,
  'Team': 'Nuggets',
  'Use': 29},
 {'2P': 52,
  '3F': 45,
  '3P': 39,
  'ASTw': 25,
  'BLKw': 2,
  'DREBw': 7,
  'FD': 7,
  'FT': 86,
  'OREBw': 2,
  'PFw': 5,
  'Player': 'Jamal Murray',
  'STLw': 7,
  'TOV': 9,
  'Team': 'Nuggets',
  'Use': 24},
 {'2P': 55,
  '3F': 58,
  '3P': 40,
  'ASTw': 4,
  'BLKw': 4,
  'DREBw': 13,
  'FD': 4,
  'FT': 77,
  'OREBw': 6,
  'PFw': 6,
  'Player': 'Michael Porter Jr.',
  'STLw': 5,
  'TOV': 6,
  'Team': 'Nuggets',
  'Use': 16},
 {'2P': 60,
  '3F': 20,
  '3P': 34,
  'ASTw': 12,
  'BLKw': 5,
  'DREBw': 11,
  'FD': 8,
  'FT': 70,
  'OREBw': 10,
  'PFw': 8,
  'Player': 'Aaron Gordon',
  'STLw': 6,
  'TOV': 9,
  'Team': 'Nuggets',
  'Use': 12},
 {'2P': 56,
  '3F': 35,
  '3P': 38,
  'ASTw': 7,
  'BLKw': 3,
  'DREBw': 7,
  'FD': 5,
  'FT': 78,
  'OREBw': 5,
  'PFw': 7,
  'Player': 'Christian Braun',
  'STLw': 8,
  'TOV': 7,
  'Team': 'Nuggets',
  'Use': 8},
 {'2P': 50,
  '3F': 22,
  '3P': 32,
  'ASTw': 20,
  'BLKw': 2,
  'DREBw': 10,
  'FD': 9,
  'FT': 66,
  'OREBw': 5,
  'PFw': 7,
  'Player': 'Russell Westbrook',
  'STLw': 9,
  'TOV': 13,
  'Team': 'Nuggets',
  'Use': 6},
 {'2P': 51,
  '3F': 32,
  '3P': 31,
  'ASTw': 4,
  'BLKw': 10,
  'DREBw': 6,
  'FD': 4,
  'FT': 68,
  'OREBw': 4,
  'PFw': 7,
  'Player': 'Peyton Watson',
  'STLw': 5,
  'TOV': 10,
  'Team': 'Nuggets',
  'Use': 3},
 {'2P': 46,
  '3F': 70,
  '3P': 36,
  'ASTw': 3,
  'BLKw': 1,
  'DREBw': 3,
  'FD': 3,
  'FT': 80,
  'OREBw': 2,
  'PFw': 3,
  'Player': 'Julian Strawther',
  'STLw': 3,
  'TOV': 8,
  'Team': 'Nuggets',
  'Use': 2}]
teams={r['Team']:r for r in TEAM_ROWS}
players_by_team={}
for r in PLAYER_ROWS: players_by_team.setdefault(r['Team'],[]).append(r)
def safe_range(start,end):
    if end < start or end <= 0: return '-'
    start=max(1,start); end=min(100,end)
    return '-' if end<start else (f'{start:02d}-{end:02d}' if end<100 else f'{start:02d}-100')
def nrange(n):
    n=int(round(n))
    if n<=0: return '-'
    n=min(100,n); return f'01-{n:02d}' if n<100 else '01-100'
def quarter_split(poss_each):
    q=[poss_each//4]*4
    for i in range(poss_each%4): q[i]+=1
    return q
def allocate(team,event):
    attr={'Use':'Use','AST':'ASTw','OREB':'OREBw','DREB':'DREBw','STL':'STLw','BLK':'BLKw','PF':'PFw'}[event]
    items=[(p['Player'],p[attr]) for p in players_by_team[team] if p[attr]>0]
    total=sum(w for _,w in items)
    if event=='Use' and total==100:
        out=[]; st=1
        for name,w in items:
            en=st+w-1; out.append((name,safe_range(st,en),w)); st=en+1
        return out
    exact=[]
    for i,(name,w) in enumerate(items):
        raw=w*100/total; exact.append([i,name,w,math.floor(raw),raw-math.floor(raw)])
    remaining=100-sum(x[3] for x in exact)
    for x in sorted(exact,key=lambda z:(z[4],z[2]),reverse=True)[:remaining]: x[3]+=1
    exact.sort(key=lambda z:z[0])
    out=[]; st=1
    for _,name,w,cnt,_ in exact:
        en=st+cnt-1; out.append((name,safe_range(st,en),w)); st=en+1
    return out
def use_map(team): return {n:r for n,r,w in allocate(team,'Use')}
def matchup_static(away,home):
    a=teams[away]; h=teams[home]; poss=round((a['Pace']+h['Pace'])/2); q=quarter_split(poss)
    def side(off,deff):
        def_adj=math.floor(deff['DEF']/PARAMS['defense_shot_divisor'])
        return {'orb':max(5,min(45,PARAMS['orb_base']+off['ORB']-deff['DRB'])),'block':max(0,min(40,PARAMS['block_base']+deff['DEF'])),'ast2':max(0,min(95,off['AST']+PARAMS['ast_mod'])),'ast3':max(0,min(95,off['AST']+8+PARAMS['ast_mod'])),'def_adj':def_adj}
    return {'poss':poss,'q':q,'away':side(a,h),'home':side(h,a)}
def player_rows(off,deff):
    off_t=teams[off]; def_t=teams[deff]; uses=use_map(off); def_adj=math.floor(def_t['DEF']/PARAMS['defense_shot_divisor']); out=[]
    for p in players_by_team[off]:
        tov=max(0,round((p['TOV']+def_t['TO Press']-off_t['TO Protect']+PARAMS['global_tov_mod'])*PARAMS['tov_scale']))
        fd=max(0,round((p['FD']+off_t['Foul Draw']-def_t['Foul Disc']+PARAMS['global_fd_mod'])*PARAMS['fd_scale']))
        three=max(0,min(95,p['3F']+off_t['3PT Tend']+PARAMS['three_mod']))
        p2=max(1,min(99,p['2P']+off_t['ShotQ']-def_adj+PARAMS['global_shot_mod']))
        p3=max(1,min(99,p['3P']+off_t['ShotQ']-def_adj+PARAMS['global_shot_mod']))
        out.append({'Offense':off,'Defense':deff,'Player':p['Player'],'Use':uses[p['Player']],'TOV':safe_range(1,tov),'Foul':safe_range(tov+1,tov+fd),'Shot':safe_range(tov+fd+1,100),'3PA':nrange(three),'2P Make':nrange(p2),'3P Make':nrange(p3),'FT':nrange(p['FT'])})
    return out
def assignment_rows(team):
    events=['Use','AST','OREB','DREB','STL','BLK','PF']; maps={e:{n:r for n,r,w in allocate(team,e)} for e in events}; out=[]
    for p in players_by_team[team]: out.append({'Team':team,'Player':p['Player'],**{e:maps[e].get(p['Player'],'-') for e in events}})
    return out
def write_csv(path, rows):
    if not rows: return
    with open(path,'w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
def html_table(headers, rows):
    s='<table><thead><tr>'+''.join(f'<th>{html.escape(str(h))}</th>' for h in headers)+'</tr></thead><tbody>'
    for row in rows: s+='<tr>'+''.join(f'<td>{html.escape(str(c))}</td>' for c in row)+'</tr>'
    return s+'</tbody></table>'
def write_html(path, away, home):
    st=matchup_static(away,home); sections=[f'<h1>{away} at {home} - Matchup Game Card</h1>']
    sections.append(html_table(['Item','Value'],[['Possessions per team',st['poss']],['Quarter split',f"Q1 {st['q'][0]} / Q2 {st['q'][1]} / Q3 {st['q'][2]} / Q4 {st['q'][3]}"],['Loose foul check','01-07'],['Steal on turnover','01-60']]))
    sections.append(html_table(['Offense','ORB on missed shot','Block chance on missed 2PA','Assist made 2','Assist made 3','Defense shot adj'],[[away,nrange(st['away']['orb']),nrange(st['away']['block']),nrange(st['away']['ast2']),nrange(st['away']['ast3']),f"-{st['away']['def_adj']}"],[home,nrange(st['home']['orb']),nrange(st['home']['block']),nrange(st['home']['ast2']),nrange(st['home']['ast3']),f"-{st['home']['def_adj']}"]]))
    for off,deff in [(away,home),(home,away)]:
        rows=[[r['Player'],r['Use'],r['TOV'],r['Foul'],r['Shot'],r['3PA'],r['2P Make'],r['3P Make'],r['FT']] for r in player_rows(off,deff)]
        sections.append(f'<h2>{off} offense vs {deff} defense</h2>'+html_table(['Player','Use','TOV','Foul','Shot','3PA?','2P make','3P make','FT'],rows))
    sections.append('<div class="pagebreak"></div><h1>Assignment Matrix</h1>')
    for team in [away,home]:
        rows=[[r['Player'],r['Use'],r['AST'],r['OREB'],r['DREB'],r['STL'],r['BLK'],r['PF']] for r in assignment_rows(team)]
        sections.append(f'<h2>{team}</h2>'+html_table(['Player','Use','AST','OREB','DREB','STL','BLK','PF'],rows))
    css='<style>@page{size:landscape;margin:0.35in}body{font-family:Arial,sans-serif;font-size:11px;color:#111827}h1{text-align:center;font-size:20px;margin:0 0 6px}h2{font-size:14px;margin:10px 0 4px}table{border-collapse:collapse;width:100%;margin:4px 0 8px}th{background:#111827;color:white}th,td{border:1px solid #9CA3AF;padding:3px 4px;text-align:left}tr:nth-child(even) td{background:#F3F4F6}.pagebreak{page-break-before:always}</style>'
    open(path,'w').write('<!doctype html><html><head><meta charset="utf-8">'+css+'</head><body>'+'\n'.join(sections)+'</body></html>')
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--away',default='Thunder'); ap.add_argument('--home',default='Knicks'); ap.add_argument('--outdir',default='generated_cards'); ap.add_argument('--list-teams',action='store_true')
    args=ap.parse_args();
    if args.list_teams:
        print(', '.join(sorted(teams))); return
    if args.away not in teams or args.home not in teams or args.away==args.home: raise SystemExit('Choose two different teams from: '+', '.join(sorted(teams)))
    os.makedirs(args.outdir,exist_ok=True); stem=f"{args.away}_at_{args.home}".replace(' ','_')
    write_html(os.path.join(args.outdir,stem+'_game_card.html'),args.away,args.home)
    write_csv(os.path.join(args.outdir,stem+'_player_ranges.csv'),player_rows(args.away,args.home)+player_rows(args.home,args.away))
    write_csv(os.path.join(args.outdir,stem+'_away_assignment.csv'),assignment_rows(args.away))
    write_csv(os.path.join(args.outdir,stem+'_home_assignment.csv'),assignment_rows(args.home))
    print('Wrote game card files to', os.path.abspath(args.outdir))
if __name__=='__main__': main()
